Camera: {Focal: 13.971313932573906, High: 650.0}

Center: {Camera_high: 670, Center_X: 381, Center_Y: 233, Front: 0, Horizon: 173, Inner: 49,
  Outer: 272, X: 308, Y: 266}
FPS: 64
HSV:
  Ball: [13, 41, 39, 100, 59, 100]
  Blue: [187, 261, 61, 98, 19, 67]
  Green: [113, 208, 51, 70, 14, 33]
  White: [0, 360, 0, 27, 0, 31]
  Yellow: [44, 70, 8, 56, 20, 86]
  black: {angle: 3, gray: 24}
  white: {angle: 3, gray: 158}
Parameterbutton: 4
SCAN: {Angle_Near_Gap: 4, Angle_range_1: 0, Angle_range_2_3: 0, Dont_Search_Angle_1: 47,
  Dont_Search_Angle_2: 164, Dont_Search_Angle_3: 285, Magn_Far_End: 245, Magn_Far_Start: 133,
  Magn_Middle_Start: 86, Magn_Near_Gap: 2, Magn_Near_Start: 52}

blackItem: {angle: 3, gray: 40}
whiteline: {angle: 4, gray: 100}
