Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 545, Center_X: 327, Center_Y: 250, Front: 270, Horizon: 157,
  Inner: 51, Outer: 228, X: 308, Y: 266}
FPS: 17
HSV:
  Ball: [0, 54, 30, 100, 30, 100]
  Blue: [203, 236, 82, 100, 0, 100]
  Green: [120, 200, 52, 93, 40, 100]
  White: [0, 359, 0, 22, 0, 23]
  Yellow: [32, 80, 29, 100, 0, 100]
  black: {angle: 3, gray: 26}
  white: {angle: 3, gray: 203}
Parameterbutton: 7
SCAN: {Angle_Near_Gap: 5, Angle_range_1: 2, Angle_range_2_3: 2, Dont_Search_Angle_1: 329,
  Dont_Search_Angle_2: 90, Dont_Search_Angle_3: 212, Magn_Far_End: 228, Magn_Far_Start: 154,
  Magn_Middle_Start: 96, Magn_Near_Gap: 2, Magn_Near_Start: 41}
blackItem: {angle: 3, gray: 40}
whiteline: {angle: 4, gray: 100}
