Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 645, Center_X: 327, Center_Y: 248, Front: 268, Horizon: 186,
  Inner: 61, Outer: 282, X: 308, Y: 266}
FPS: 17
HSV:
  Ball: [0, 54, 28, 93, 30, 100]
  Blue: [203, 236, 82, 100, 0, 100]
  Green: [172, 202, 31, 86, 36, 85]
  White: [0, 359, 0, 22, 0, 23]
  Yellow: [32, 80, 32, 100, 0, 100]
  black: {angle: 3, gray: 26}
  white: {angle: 3, gray: 205}
Parameterbutton: 7
SCAN: {Angle_Near_Gap: 6, Angle_range_1: 2, Angle_range_2_3: 2, Dont_Search_Angle_1: 90,
  Dont_Search_Angle_2: 331, Dont_Search_Angle_3: 213, Magn_Far_End: 254, Magn_Far_Start: 191,
  Magn_Middle_Start: 103, Magn_Near_Gap: 3, Magn_Near_Start: 41}
blackItem: {angle: 3, gray: 40}
whiteline: {angle: 4, gray: 100}
