Camera:
  Focal: 13.971313932573906
  High: 650.0
Center:
  Camera_high: 670
  Center_X: 404
  Center_Y: 308
  Front: 2
  Horizon: 257
  Inner: 60
  Outer: 300
  X: 308
  Y: 266
FPS: 20
HSV:
  Ball:
  - 0
  - 12
  - 56
  - 100
  - 6
  - 100
  Blue:
  - 201
  - 230
  - 57
  - 100
  - 24
  - 100
  Green:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  White:
  - 0
  - 360
  - 0
  - 27
  - 0
  - 31
  Yellow:
  - 17
  - 54
  - 41
  - 100
  - 21
  - 100
  black:
    angle: 20
    gray: 20
  white:
    angle: 1
    gray: 170
Parameterbutton: 4
SCAN:
  Angle_Near_Gap: 5
  Angle_range_1: 0
  Angle_range_2_3: 0
  Dont_Search_Angle_1: 47
  Dont_Search_Angle_2: 164
  Dont_Search_Angle_3: 285
  Magn_Far_End: 265
  Magn_Far_Start: 186
  Magn_Middle_Start: 113
  Magn_Near_Gap: 4
  Magn_Near_Start: 52
blackItem:
  angle: 3
  gray: 40
whiteline:
  angle: 4
  gray: 100
