Camera:
  Focal: 13.971313932573906
  High: 650.0
Center:
  Camera_high: 650
  Center_X: 319
  Center_Y: 238
  Front: 4
  Horizon: 188
  Inner: 54
  Outer: 272
  X: 308
  Y: 266
FPS: 17
HSV:
  Ball:
  - 4
  - 26
  - 64
  - 90
  - 28
  - 100
  Blue:
  - 187
  - 261
  - 61
  - 98
  - 29
  - 100
  Green:
  - 139
  - 185
  - 25
  - 60
  - 0
  - 66
  White:
  - 0
  - 360
  - 0
  - 27
  - 0
  - 31
  Yellow:
  - 39
  - 67
  - 45
  - 70
  - 26
  - 100
  black:
    angle: 3
    gray: 30
  white:
    angle: 3
    gray: 170
Parameterbutton: 4
SCAN:
  Angle_Near_Gap: 4
  Angle_range_1: 0
  Angle_range_2_3: 0
  Dont_Search_Angle_1: 47
  Dont_Search_Angle_2: 164
  Dont_Search_Angle_3: 285
  Magn_Far_End: 267
  Magn_Far_Start: 192
  Magn_Middle_Start: 121
  Magn_Near_Gap: 4
  Magn_Near_Start: 52
blackItem:
  angle: 3
  gray: 40
whiteline:
  angle: 4
  gray: 100
